Feature/tweaks
nhsuk/pa11y-dashboard pull request #9
Opened 2018-09-13 14:52 UTC by st3v3nhunt

2018-09-13 15:13 UTC, mcheung-nhs requested changes

2018-09-13 15:13 UTC, mcheung-nhs commented on README.md
> +the more needs to be read/write. Removing the setting from the Dockerfile will
the more needs to be...
should this be 'the mode needs to be...' ?

2018-09-14 07:54 UTC, st3v3nhunt commented
Good spot. I've fixed that and made some additional wording changes.

2018-09-14 08:40 UTC, mcheung-nhs requested changes

2018-09-14 08:40 UTC, mcheung-nhs commented on README.md
> +The deployment is initiated from the [./scripts/deploy](./scripts/deploy)
deploy.sh ?

2018-09-14 08:40 UTC, mcheung-nhs commented on README.md
> +`READONLY=false`, as specified [above](./#running-in-development).
internal link not working for 'above'

2018-09-14 09:12 UTC, st3v3nhunt commented on README.md
> +The deployment is initiated from the [./scripts/deploy](./scripts/deploy)
Thanks, sorted!

2018-09-14 09:12 UTC, st3v3nhunt commented on README.md
> +`READONLY=false`, as specified [above](./#running-in-development).
Thanks, sorted!

2018-09-14 09:50 UTC, mcheung-nhs approved these changes

2018-09-14 09:51 UTC, mcheung-nhs approved these changes

2018-09-14 09:51 UTC, merged